const bcrypt = require('bcryptjs');

/**
 * @param {import('knex').Knex} knex
 */
exports.seed = async (knex) => {
  // Delete in FK order
  await knex('offer_claims').del().catch(() => {});
  await knex('card_requests').del().catch(() => {});
  await knex('concierge_requests').del().catch(() => {});
  await knex('gift_claims').del().catch(() => {});
  await knex('tier_rewards').del().catch(() => {});
  await knex('redemption_history').del();
  await knex('tier_history').del();
  await knex('points_transactions').del();
  await knex('clients').del();

  const passwordHash = await bcrypt.hash('Test1234!', 12);

  // All clients start at 0 points / bronze tier.
  // The transaction seed (004) processes AxisCare invoices and updates final state.
  await knex('clients').insert([
    // =============================================
    // TEXAS — Dallas-Fort Worth (11 clients, 39%)
    // =============================================
    {
      axiscare_client_id: 'AC-10001',
      name: 'Alice Johnson',
      email: 'alice@example.com',
      phone: '(214) 555-0101',
      address_street: '123 Oak Ln',
      address_city: 'Dallas',
      address_state: 'TX',
      address_zip: '75201',
      market: 'Dallas-Fort Worth',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-02-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10002',
      name: 'Bob Smith',
      email: 'bob@example.com',
      phone: '(972) 555-0202',
      address_street: '456 Elm St',
      address_city: 'Plano',
      address_state: 'TX',
      address_zip: '75024',
      market: 'Dallas-Fort Worth',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-05-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10003',
      name: 'Carol Williams',
      email: 'carol@example.com',
      phone: '(469) 555-0303',
      address_street: '789 Maple Dr',
      address_city: 'Frisco',
      address_state: 'TX',
      address_zip: '75034',
      market: 'Dallas-Fort Worth',
      care_package: 'white_glove',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-03-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10004',
      name: 'David Brown',
      email: 'david@example.com',
      phone: '(817) 555-0404',
      address_street: '321 Cedar Ave',
      address_city: 'Fort Worth',
      address_state: 'TX',
      address_zip: '76102',
      market: 'Dallas-Fort Worth',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-01-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10005',
      name: 'Eve Davis',
      email: 'eve@example.com',
      phone: '(214) 555-0505',
      address_street: '555 Highland Park Blvd',
      address_city: 'Highland Park',
      address_state: 'TX',
      address_zip: '75205',
      market: 'Dallas-Fort Worth',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-06-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10006',
      name: 'Frank Martinez',
      email: 'frank@example.com',
      phone: '(214) 555-0606',
      address_street: '900 Preston Rd',
      address_city: 'Dallas',
      address_state: 'TX',
      address_zip: '75230',
      market: 'Dallas-Fort Worth',
      care_package: 'white_glove',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: false,
      unenrolled_at: '2025-09-15T10:00:00Z',
      unenroll_reason: 'deceased',
      created_at: '2024-01-15T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10007',
      name: 'Grace Kim',
      email: 'grace@example.com',
      phone: '(972) 555-0707',
      address_street: '1200 Legacy Dr',
      address_city: 'Plano',
      address_state: 'TX',
      address_zip: '75024',
      market: 'Dallas-Fort Worth',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-08-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10008',
      name: 'Henry Chen',
      email: 'henry@example.com',
      phone: '(469) 555-0808',
      address_street: '3400 Turtle Creek Blvd',
      address_city: 'Dallas',
      address_state: 'TX',
      address_zip: '75219',
      market: 'Dallas-Fort Worth',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-08-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10009',
      name: 'Isabella Rodriguez',
      email: 'isabella@example.com',
      phone: '(817) 555-0909',
      address_street: '7700 Camp Bowie Blvd',
      address_city: 'Fort Worth',
      address_state: 'TX',
      address_zip: '76116',
      market: 'Dallas-Fort Worth',
      care_package: 'white_glove',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: false,
      unenrolled_at: '2025-11-01T10:00:00Z',
      unenroll_reason: 'switched_provider',
      created_at: '2024-06-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10010',
      name: 'James Wilson',
      email: 'james@example.com',
      phone: '(214) 555-1010',
      address_street: '4500 McKinney Ave',
      address_city: 'Dallas',
      address_state: 'TX',
      address_zip: '75205',
      market: 'Dallas-Fort Worth',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-04-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10011',
      name: 'Karen Thompson',
      email: 'karen@example.com',
      phone: '(972) 555-1111',
      address_street: '2800 Southlake Blvd',
      address_city: 'Southlake',
      address_state: 'TX',
      address_zip: '76092',
      market: 'Dallas-Fort Worth',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2026-01-01T10:00:00Z'
    },

    // =============================================
    // FLORIDA — South Florida (6 clients, 21%)
    // =============================================
    {
      axiscare_client_id: 'AC-10012',
      name: 'Luis Garcia',
      email: 'luis@example.com',
      phone: '(305) 555-1212',
      address_street: '800 Brickell Ave',
      address_city: 'Miami',
      address_state: 'FL',
      address_zip: '33131',
      market: 'South Florida',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-04-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10013',
      name: 'Maria Nguyen',
      email: 'maria@example.com',
      phone: '(954) 555-1313',
      address_street: '2200 Las Olas Blvd',
      address_city: 'Fort Lauderdale',
      address_state: 'FL',
      address_zip: '33301',
      market: 'South Florida',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-07-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10014',
      name: 'Nathan Patel',
      email: 'nathan@example.com',
      phone: '(561) 555-1414',
      address_street: '500 E Palmetto Park Rd',
      address_city: 'Boca Raton',
      address_state: 'FL',
      address_zip: '33432',
      market: 'South Florida',
      care_package: 'white_glove',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-09-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10015',
      name: 'Olivia Anderson',
      email: 'olivia@example.com',
      phone: '(305) 555-1515',
      address_street: '300 Alhambra Cir',
      address_city: 'Coral Gables',
      address_state: 'FL',
      address_zip: '33134',
      market: 'South Florida',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: false,
      unenrolled_at: '2025-12-01T10:00:00Z',
      unenroll_reason: 'financial',
      created_at: '2025-02-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10016',
      name: 'Patricia Moore',
      email: 'patricia@example.com',
      phone: '(954) 555-1616',
      address_street: '1500 Weston Rd',
      address_city: 'Weston',
      address_state: 'FL',
      address_zip: '33327',
      market: 'South Florida',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-05-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10017',
      name: 'Robert Taylor',
      email: 'robert@example.com',
      phone: '(561) 555-1717',
      address_street: '100 Atlantic Ave',
      address_city: 'Delray Beach',
      address_state: 'FL',
      address_zip: '33483',
      market: 'South Florida',
      care_package: 'white_glove',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-10-01T10:00:00Z'
    },

    // =============================================
    // ARIZONA — Phoenix Metro (4 clients, 14%)
    // =============================================
    {
      axiscare_client_id: 'AC-10018',
      name: 'Sandra Lee',
      email: 'sandra@example.com',
      phone: '(480) 555-1818',
      address_street: '7000 E Camelback Rd',
      address_city: 'Scottsdale',
      address_state: 'AZ',
      address_zip: '85251',
      market: 'Phoenix Metro',
      care_package: 'white_glove',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-03-15T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10019',
      name: 'Thomas Wright',
      email: 'thomas@example.com',
      phone: '(602) 555-1919',
      address_street: '200 W Washington St',
      address_city: 'Phoenix',
      address_state: 'AZ',
      address_zip: '85004',
      market: 'Phoenix Metro',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-10-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10020',
      name: 'Victoria Adams',
      email: 'victoria@example.com',
      phone: '(480) 555-2020',
      address_street: '3200 W Chandler Blvd',
      address_city: 'Chandler',
      address_state: 'AZ',
      address_zip: '85225',
      market: 'Phoenix Metro',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: false,
      unenrolled_at: '2025-10-15T10:00:00Z',
      unenroll_reason: 'no_longer_needs_care',
      created_at: '2025-03-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10021',
      name: 'William Harris',
      email: 'william@example.com',
      phone: '(623) 555-2121',
      address_street: '5800 W Glendale Ave',
      address_city: 'Glendale',
      address_state: 'AZ',
      address_zip: '85301',
      market: 'Phoenix Metro',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-09-01T10:00:00Z'
    },

    // =============================================
    // SOUTH CAROLINA — Charleston (3 clients, 11%)
    // =============================================
    {
      axiscare_client_id: 'AC-10022',
      name: 'Diana Cooper',
      email: 'diana@example.com',
      phone: '(843) 555-2222',
      address_street: '100 Market St',
      address_city: 'Charleston',
      address_state: 'SC',
      address_zip: '29401',
      market: 'Charleston',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-06-15T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10023',
      name: 'Edward Mitchell',
      email: 'edward@example.com',
      phone: '(843) 555-2323',
      address_street: '450 Coleman Blvd',
      address_city: 'Mount Pleasant',
      address_state: 'SC',
      address_zip: '29464',
      market: 'Charleston',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-01-15T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10024',
      name: 'Fiona Roberts',
      email: 'fiona@example.com',
      phone: '(843) 555-2424',
      address_street: '200 N Main St',
      address_city: 'Summerville',
      address_state: 'SC',
      address_zip: '29483',
      market: 'Charleston',
      care_package: 'white_glove',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: false,
      unenrolled_at: '2025-08-20T10:00:00Z',
      unenroll_reason: 'dissatisfied',
      created_at: '2024-11-01T10:00:00Z'
    },

    // =============================================
    // SOUTH DAKOTA — Sioux Falls (4 clients, 14%)
    // =============================================
    {
      axiscare_client_id: 'AC-10025',
      name: 'George Palmer',
      email: 'george@example.com',
      phone: '(605) 555-2525',
      address_street: '300 N Phillips Ave',
      address_city: 'Sioux Falls',
      address_state: 'SD',
      address_zip: '57104',
      market: 'Sioux Falls',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2024-08-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10026',
      name: 'Hannah Brooks',
      email: 'hannah@example.com',
      phone: '(605) 555-2626',
      address_street: '1200 S Minnesota Ave',
      address_city: 'Sioux Falls',
      address_state: 'SD',
      address_zip: '57106',
      market: 'Sioux Falls',
      care_package: 'premium',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2025-03-15T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10027',
      name: 'Ian Sullivan',
      email: 'ian@example.com',
      phone: '(605) 555-2727',
      address_street: '4500 W 69th St',
      address_city: 'Sioux Falls',
      address_state: 'SD',
      address_zip: '57108',
      market: 'Sioux Falls',
      care_package: 'white_glove',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: false,
      unenrolled_at: '2026-01-10T10:00:00Z',
      unenroll_reason: 'financial',
      created_at: '2025-07-01T10:00:00Z'
    },
    {
      axiscare_client_id: 'AC-10028',
      name: 'Julia Ramirez',
      email: 'julia@example.com',
      phone: '(605) 555-2828',
      address_street: '800 Holly Blvd',
      address_city: 'Brandon',
      address_state: 'SD',
      address_zip: '57005',
      market: 'Sioux Falls',
      care_package: 'essentials',
      current_tier: 'bronze',
      lifetime_points: 0,
      redeemable_points: 0,
      password_hash: passwordHash,
      is_active: true,
      created_at: '2026-01-15T10:00:00Z'
    }
  ]);
};
